weather_api_sample_response = {
    "location": {
        "name": "Seattle",
        "region": "Washington",
        "country": "USA",
        "lat": 47.63,
        "lon": -122.34,
        "tz_id": "America/Los_Angeles",
        "localtime_epoch": 1682715015,
        "localtime": "2023-04-28 13:50",
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2022-05-01",
                "date_epoch": 1651363200,
                "day": {
                    "maxtemp_c": 17.5,
                    "maxtemp_f": 63.6,
                    "mintemp_c": 4.5,
                    "mintemp_f": 40.1,
                    "avgtemp_c": 11.1,
                    "avgtemp_f": 52.0,
                    "maxwind_mph": 4.7,
                    "maxwind_kph": 7.6,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "avgvis_km": 7.1,
                    "avgvis_miles": 4.0,
                    "avghumidity": 74.0,
                    "condition": {
                        "text": "Overcast",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                        "code": 1009,
                    },
                    "uv": 4.0,
                },
                "astro": {
                    "sunrise": "05:52 AM",
                    "sunset": "08:22 PM",
                    "moonrise": "06:20 AM",
                    "moonset": "09:40 PM",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": "0",
                },
                "hour": [
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                    {"condition": {}},
                ],
            },
        ]
    },
}
